spring:
  application:
    name: teacher-bot

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/teacher_bot
    username: postgres
    password: 1


server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    default-models-expand-depth: 0
    doc-expansion: list
  api-docs:
    path: /v3/api-docs
  webjars:
    prefix: /webjars

app:
  jwt:
    secret: 7EDUTeacherBotSecretKeyForJWTTokenGeneration2024VeryLongSecretKey
    expiration: 86400000  # 24 hours
  storage:
    base-path: ./storage/languages
